# Generated by Django 4.0.6 on 2022-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('txn_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('txn_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.CharField(max_length=12)),
                ('payer_name', models.CharField(max_length=100)),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('test', models.BooleanField(default=False)),
            ],
        ),
    ]
