# Generated by Django 4.0.6 on 2022-08-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('txn_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('txn_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
