# Generated by Django 4.0.6 on 2022-08-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_cancel_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='exist',
            field=models.BooleanField(default=True),
        ),
    ]
