# Generated by Django 4.0.6 on 2022-08-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_cancelpayment_delete_cancel_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelpayment',
            name='is_fav',
        ),
        migrations.AddField(
            model_name='cancelpayment',
            name='exist',
            field=models.BooleanField(default=True),
        ),
    ]
