# Generated by Django 4.0.6 on 2022-08-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_remove_cancelpayment_is_fav_cancelpayment_exist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelpayment',
            name='user',
        ),
    ]
