# Generated by Django 4.0.6 on 2022-08-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_remove_cancelpayment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='test',
        ),
        migrations.AlterField(
            model_name='payment',
            name='login',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
